server:
  port: 8080
  tomcat:
    accept-count: 1024
    max-connections: 4096
    connection-timeout: 3000

spring:
  main:
    banner-mode: off
  jmx:
    enabled: false
  threads:
    virtual:
      enabled: true
  jackson:
    deserialization:
      fail-on-unknown-properties: false

logging:
  level:
    root: WARN
    br.com.murilovieira: INFO
